---
{{- /*
This template will create a single Red Hat Data Grid cluster using the
`Infinispan` custom resource.
*/}}
{{- if .Values.infinispan.enabled -}}
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: {{ .Values.infinispan.name }}
  {{- if .Values.infinispan.monitoring.disablePrometheus }}
  annotations:
    infinispan.org/monitoring: 'false'
  {{- end }}
spec:
  replicas: {{ .Values.infinispan.replicas }}
  version: {{ .Values.infinispan.version }}
  service:
    type: DataGrid
  {{- if .Values.infinispan.customConfig.enabled }}
  configMapName: {{ .Release.Name }}-datagrid-custom-config
  {{- end }}
  upgrades:
    type: {{ .Values.infinispan.upgradeType }}
  {{- if .Values.infinispan.disableConfigListener }}
  configListener:
    enabled: false
  {{- end }}
  expose:
    type: {{ .Values.infinispan.expose.type }}
  {{- if eq "Route" .Values.infinispan.expose.type }}
    host: {{ .Values.infinispan.expose.hostname }}
  {{- else if and (eq "NodePort" .Values.infinispan.expose.type) }}
    nodePort: {{ .Values.infinispan.expose.port }}
  {{- else if eq "LoadBalancer" .Values.infinispan.expose.type }}
    port: {{ default 11222 .Values.infinispan.expose.port }}
  {{- end }}
  {{-if .Values.infinispan.monitoring.enableJMX }}
  jmx:
    enabled: true
  {{- end }}
{{- end -}}